# Use an official PostgreSQL as a parent image
FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# Expose the PostgreSQL port


COPY /Infrastructure/init.sql /docker-entrypoint-initdb.d/

